### ISSUE TITLE
ZPA PLSQL plugin - is unable to pickup Quality Profile automatically when scanning .pb files 

### ISSUE THREAD

**Issue by csrvsk** [felipebz/zpa#162] opened 2022-06-08 12:25 UTC
Hi, I am using SonarQube command line to scan the project which consists of .pb files. For which I have added ZPA -PLSQL open source plugin.
When I ran the scan, project is created in Sonar dashboard but the results are empty and the reason it is unable to pickup the quality profile for the type of files.
Initially I thought the reason was, since ZPA plugin is not native in Community Edition of SQ.
But surprisingly when I rans the scan on a project which is consisting of .sql files which are defined by default with this plugin, SonarQube was able to pickup Quality Profile for .sql files.

Please let me know if there is a workaround without using Sonar GUI.

**Comment by felipebz** [comment] 2022-06-09 10:59
Hi,

You can use the property `sonar.zpa.file.suffixes` (File Suffixes) on "Administration" > "Z PL/SQL Analyzer" to set what file extensions should by analyzed by the plugin.

By default, it analyses files with the extension sql, pkg, pks and pkb, but you're free to change them and add any extension you need.

**Comment by csrvsk** [comment] 2022-06-13 22:58
yeah i tried that but it is not picking up .pb files. But it is for .sql files.
as i can see only 4 types of default extensions are there by default.

![image](https://user-images.githubusercontent.com/70667412/173461120-ddc36736-6b88-4a83-bec4-ee31c964c0d9.png)

**Comment by felipebz** [comment] 2022-06-14 00:29
That's weird, it should work. You can try to re-run the analysis passing the option `-X` to SonarScanner to enable more logs. It'll show something like this:

```
(...)
INFO: Indexing files...
INFO: Project configuration:
INFO:   Excluded sources: **/*.min.*, **/jquery.js, **/*.Designer.cs
DEBUG: 'src\file1.sql' indexed with language 'plsqlopen'
DEBUG: 'src\file2.pb' indexed with language 'plsqlopen'
INFO: 2 files indexed
(...)
```

As shown in the example, the .pb file was correctly indexed with the language "plsqlopen", which means it'll analyzed by this plugin.

**Comment by csrvsk** [comment] 2022-06-14 13:23
Hi, I am wondering if there is way to recompile the plugin source code in such way that it makes .pb files as default along with the extension sql, pkg, pks and pkb.

please advice accordingly. The reason I am asking for this is I want to make this possible without using sonar GUI.
Hope you understand my concern.

**Comment by felipebz** [comment] 2022-06-14 16:25
If you don't want to set this parameter on SonarQube UI, you can pass the property to the SonarScanner:

`sonar-scanner -Dsonar.zpa.file.suffixes=sql,pkg,pks,pkb,pb ...`

**Comment by csrvsk** [comment] 2022-06-14 16:49
I tried the command before and it didn't work

**Comment by csrvsk** [comment] 2022-06-14 16:59
> Hi, I am wondering if there is way to recompile the plugin source code in such way that it makes .pb files as default along with the extension sql, pkg, pks and pkb.

please let me know

**Comment by felipebz** [comment] 2022-06-14 22:00
You need to pass `-X` flag to sonar-scanner to show you the debug output, which contains the info I mentioned on a previous comment.

> Hi, I am wondering if there is way to recompile the plugin source code in such way that it makes .pb files as default along with the extension sql, pkg, pks and pkb.

Sure, the default values are defined on the PlSqlPlugin class: https://github.com/felipebz/zpa/blob/c1e29f5f679a588d3290c0a426e970e16efa7db5/sonar-zpa-plugin/src/main/kotlin/org/sonar/plsqlopen/PlSqlPlugin.kt#L41

You could change it and recompile the project, but I'm confident that it won't fix the root cause of your problem. It's the same thing as setting this value using the SonarQube UI or setting the property on the analysis.

**Closed** 2022-06-23 13:42 UTC
